//
// Created by ersong2 on 2025/4/23.
//

#ifndef ORG_GRAPH_OUTSIDE_NATIVELIBRARY_H
#define ORG_GRAPH_OUTSIDE_NATIVELIBRARY_H

#endif //ORG_GRAPH_OUTSIDE_NATIVELIBRARY_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graph_outside_NativeLibrary */

#ifndef _Included_org_graph_outside_NativeLibrary
#define _Included_org_graph_outside_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     org_graph_outside_NativeLibrary
     * Method:    generateLayout
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_org_graph_outside_NativeLibrary_generateLayout
      (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
